# Generated by Django 5.1.1 on 2024-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('published_date', models.DateField()),
                ('copies_available', models.IntegerField()),
                ('available_sw_cpy', models.BooleanField(default=False)),
            ],
        ),
    ]
