# Generated by Django 5.1 on 2024-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
